//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NW.UnivariateForecasting.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NW.UnivariateForecasting.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ObservationName&quot;: null,
        ///  &quot;Values&quot;: [
        ///    58.5,
        ///    615.26
        ///  ],
        ///  &quot;Coefficient&quot;: null,
        ///  &quot;Error&quot;: null,
        ///  &quot;Steps&quot;: 1
        ///}.
        /// </summary>
        internal static string ForecastingInitBareMinimumAsJson {
            get {
                return ResourceManager.GetString("ForecastingInitBareMinimumAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///  &quot;Values&quot;: [
        ///    58.5,
        ///    615.26,
        ///    659.84,
        ///    635.69,
        ///    612.27,
        ///    632.94
        ///  ],
        ///  &quot;Coefficient&quot;: 0.5,
        ///  &quot;Error&quot;: 0.01,
        ///  &quot;Steps&quot;: 2
        ///}.
        /// </summary>
        internal static string ForecastingInitDoubleWithCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingInitDoubleWithCEAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///  &quot;Values&quot;: [
        ///    58.5,
        ///    615.26,
        ///    659.84,
        ///    635.69,
        ///    612.27,
        ///    632.94
        ///  ],
        ///  &quot;Coefficient&quot;: 0.5,
        ///  &quot;Error&quot;: 0.01,
        ///  &quot;Steps&quot;: 1
        ///}.
        /// </summary>
        internal static string ForecastingInitSingleWithCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingInitSingleWithCEAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///  &quot;Values&quot;: [
        ///    58.5,
        ///    615.26,
        ///    659.84,
        ///    635.69,
        ///    612.27,
        ///    632.94
        ///  ],
        ///  &quot;Coefficient&quot;: null,
        ///  &quot;Error&quot;: null,
        ///  &quot;Steps&quot;: 1
        ///}.
        /// </summary>
        internal static string ForecastingInitSingleWithoutCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingInitSingleWithoutCEAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Init&quot;: {
        ///    &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///    &quot;Values&quot;: [
        ///      58.5,
        ///      615.26,
        ///      659.84,
        ///      635.69,
        ///      612.27,
        ///      632.94
        ///    ],
        ///    &quot;Coefficient&quot;: 0.5,
        ///    &quot;Error&quot;: 0.01,
        ///    &quot;Steps&quot;: 2
        ///  },
        ///  &quot;Observations&quot;: [
        ///    {
        ///      &quot;Coefficient&quot;: 0.5,
        ///      &quot;Error&quot;: 0.01,
        ///      &quot;NextValue&quot;: 316.48
        ///    },
        ///    {
        ///      &quot;Coefficient&quot;: 0.5,
        ///      &quot;Error&quot;: 0.01,
        ///      &quot;NextValue&quot;: 613.11
        ///    }
        ///  ],
        ///  &quot;Version&quot;: &quot;3.0.0.0&quot;
        ///}.
        /// </summary>
        internal static string ForecastingSessionDoubleWithCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingSessionDoubleWithCEAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Init&quot;: {
        ///    &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///    &quot;Values&quot;: [
        ///      58.5,
        ///      615.26,
        ///      659.84,
        ///      635.69,
        ///      612.27,
        ///      632.94
        ///    ],
        ///    &quot;Coefficient&quot;: 0.5,
        ///    &quot;Error&quot;: 0.01,
        ///    &quot;Steps&quot;: 1
        ///  },
        ///  &quot;Observations&quot;: [
        ///    {
        ///      &quot;Coefficient&quot;: 0.5,
        ///      &quot;Error&quot;: 0.01,
        ///      &quot;NextValue&quot;: 316.48
        ///    }
        ///  ],
        ///  &quot;Version&quot;: &quot;3.0.0.0&quot;
        ///}.
        /// </summary>
        internal static string ForecastingSessionSingleWithCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingSessionSingleWithCEAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Init&quot;: {
        ///    &quot;ObservationName&quot;: &quot;Sales USD&quot;,
        ///    &quot;Values&quot;: [
        ///      58.5,
        ///      615.26,
        ///      659.84,
        ///      635.69,
        ///      612.27,
        ///      632.94
        ///    ],
        ///    &quot;Coefficient&quot;: null,
        ///    &quot;Error&quot;: null,
        ///    &quot;Steps&quot;: 1
        ///  },
        ///  &quot;Observations&quot;: [
        ///    {
        ///      &quot;Coefficient&quot;: 0.82,
        ///      &quot;Error&quot;: 0.22,
        ///      &quot;NextValue&quot;: 519.23
        ///    }
        ///  ],
        ///  &quot;Version&quot;: &quot;3.0.0.0&quot;
        ///}.
        /// </summary>
        internal static string ForecastingSessionSingleWithoutCEAsJson {
            get {
                return ResourceManager.GetString("ForecastingSessionSingleWithoutCEAsJson", resourceCulture);
            }
        }
    }
}
